export const TOGGLE_IS_ADMIN = "ADMIN/TOGGLE_IS_ADMIN";
export const TOGGLE_IS_LOADING = "ADMIN/TOGGLE_IS_LOADING";
export const SET_NEW_STUDENT = "ADMIN/SET_NEW_STUDENT";
export const SET_NEW_STUDENT_FIND_CODE = "ADMIN/SET_NEW_STUDENT_FIND_CODE";
export const SET_NEW_TEACHER = "ADMIN/SET_NEW_TEACHER";